### PR TITLE
Various changes to support timemap.js fork

### PR DESCRIPTION
**Pull request by nrabinowitz**
As [discussed here](https://github.com/mapstraction/mxn/pull/50#issuecomment-4147314), I merged the latest master into my fork and did my best to clean it up and resubmit the pull request. The merge for the microsoft provider code was a bit ugly, as somewhere along the line tabs were converted to spaces, making the merge trickier, so hopefully I didn't stomp on anything there.

The main changes here are still:
- fixes to BoundingBox
- click events and bubble methods on Polyline
- bubble methods on Mapstraction
- various provider-specific tweaks and fixes

Please let me know if I can help clarify any of this.

### CODE REVIEW

**Comment by dezfowler** [comment]
Just had a look at merging this in - got a couple of comments about the multiple info bubbles thing. 

Notice you have a proprietary_bubbles array and some other repeated code in each provider but I think if we were to introduce this and keep it consistent with the rest of the library we should probably have a new InfoBubble class in mxn.core.js.

My other comment is that a few providers require you to add a marker which you then hide - is this definitely required?

**Comment by nrabinowitz** [comment]
Well, the `proprietary_bubbles` array only applies to Google v3 and OpenLayers, as those are the only providers (among those I was aiming to support) that allow the option for multiple info windows. While I think it might sense to have an InfoBubble class, most providers seem to treat this as a method on the map or marker, rather than a fully independent object. I agree that it would be preferable to avoid the repeated code in Google V3 and OpenLayers, but I wonder whether it makes sense to abstract this if only two providers support it.

Not sure I understand your last comment. Do you mean other providers, ones I haven't addressed here, require a marker for a map-based info bubble? And is your question whether it's worthwhile having map-based info bubbles at all? If that's the question, then yes, I definitely see this as a requirement - not so much because it's always useful to open an info bubble at a random point on the map, but because it allows you to support info bubbles for polylines, polygons, and eventually overlays, even if they don't natively support this. In both my own projects and the projects of many folks using Timemap.js, I've repeatedly seen this requirement. See [this Timemap.js example](http://timemap.googlecode.com/svn/tags/2.0.1/examples/placemarks.html) to see Mapstraction-based clickable polylines and polygons in action.

**Comment by dezfowler** [comment]
Okay, I think if enough people think this feature offers value it's worth
doing even if not all the providers support it so long as it's possible for
Mapstraction to provide its own implementation to patch the other providers.

We can assume the usefulness is there but it's worth checking what support
for this (or features that would allow a custom implementation of this) is
like in the other providers.

I think a standalone class would be a good way to approach this regardless
of how the individual providers support it. One of the important
Mapstraction features is that you can swap providers at runtime and it
should maintain your markers, poly lines, etc and to do that it should
track its own object representing each bubble.

Derek
On Feb 25, 2012 5:24 AM, "Nick Rabinowitz" <
reply@reply.github.com>
wrote:

**Comment by bryanlarsen** [comment]
What's the status of this pull request?  Will it make the next release?   Right now we're in a situation where we use the timemap fork of mapstraction for some pages on our site and vanilla mapstraction for others due to various capability differences and bug exposure.   For us, it's the Polyline enhancements that we use in the timemap fork.

**Comment by vicchi** [comment]
Given that there's been a recent flurry of pre-release pull request merging and code tidying-up going on on the `integration` branch I'd like, in principle, to get this into v2.1

However, there's 75 commits across 11 files in this pull request. That's a lot of commits to cherry-pick, plus the code base has moved on a bit since the pull request was opened.

What would be really helpful here is if this pull request can be revisited by the author (@nrabinowitz) to see whether it needs to be closed down and another, updated pull request issued or whether this is good as it stands.

**Comment by vicchi** [comment]
As there's been no response from @nrabinowitz for over a year I'm closing this pull request. The v2.1 code base has changed significantly from that which the pull request was based on, but feel free to re-issue this based on the current code base.

**Comment by nrabinowitz** [comment]
Yes, sorry about this - I've had very little time for Timemap.js development in the past year, and as noted there's a fair amount of work to reconcile my fork with the current version. I'll open a new pull req if/when I get a chance to look at this.

**Comment by vicchi** [comment]
No apologies needed. I was just clearing up old pull requests which were getting more and more challenging to merge in as the code base diverges away from the current state of the master branch over time.

**Pull request closed without merging**
