### PR TITLE
fixed a typo, which means that openlayers icons now show as a missing pi...

### PR DESCRIPTION
**Pull request by gilesc50**
...cture, rather than not showing at all. Its not a complete fix for openlayers icons missing, but it does move it forwards.

### CODE REVIEW

**Comment by vicchi** [comment]
This is new to me ... what are we missing as far as OpenLayers support is concerned?

**Comment by gilesc50** [comment]
I don’t see any pins appear when running core tests on 2release .1 – do you?

**Comment by vicchi** [comment]
Yikes. No, I do not. Well spotted. I'll get this merged, but are you on top of getting the overall marker support sorted as well?

**Comment by gilesc50** [comment]
I wanted to, but time is not with me. Maybe ping whoever provided the patch to move it to vector features?

**Comment by vicchi** [comment]
Good call. Will do.

**Comment by vicchi** [comment]
Manually merged into `release-2.1`; see commit 2e0b334b3a0f23bb65b339037b1af5190fb63dc2

**Comment by vicchi** [comment]
Looks like this came in on Pull Request #222 via Issue #212 via @esohns-humana. I'll take a deeper look

**Comment by vicchi** [comment]
I've reopened that Pull Request and asked @esohns-humana for help on this - see https://github.com/mapstraction/mxn/pull/222#issuecomment-15455035

**Pull request closed without merging**
