### PR TITLE
Release 2.1

### PR DESCRIPTION
**Pull request by esohns-humana**
- repair missing marker click event delegation (ovi)
- repair default infoBubble close-button function (OpenLayers)

### CODE REVIEW

**Comment by vicchi** [comment]
Sorry, but there's 27 commits in this Pull Request, as there was in the previous one. This looks like a precise duplicate of Pull Request #235, with the same set of issues.

What am I missing? I'd expect maybe 2 or 3 commits maximum, one for `mxn.openlayers.core.js` and one for `mxn.ovi.core.js`.

-Gary

**Comment by vicchi** [comment]
Can you let me know which commit hashes you want implemented and I can maybe cherry pick only those changes from this Pull Request?

-Gary

**Comment by esohns-humana** [comment]
Sorry about the confusion, I should have synched with upstream before commiting.

As most previous commits have been merged already, you should now be seeing only the most recent changes.
If you tell me how I can remove those commits from the pull request without reforking, I will gladly comply.

I have tried to follow the given indentation style.

Please re-pull.

**Comment by vicchi** [comment]
OK. Thanks. I'll re-pull later this morning.

**Comment by vicchi** [comment]
I've taken a look and the pull request is still pulling in too many commits. From looking at the commit history in your `release-2.1` branch I think I need to cherry pick the following commits ...

`87a6bf0` - repair ovi support
`7a17d8b` - repair default infoBubble close button function (OpenLayers)

... does that sound right?

**Comment by esohns-humana** [comment]
Yes, that's correct. How should I commit anything new without reforking ?

**Comment by vicchi** [comment]
As a general rule of thumb, if you pull in any upstream changes into `master`, `integration` and (in this particular case where there's a dedicated release branch being used) into `release-2.1`, merge and commit to your local repository and then push to GitHub before you make any changes you want in a Pull Request you should be OK. Once this release is done, then just make sure `master` and `integration` are up to date and in sync.

Before issuing your commits, make sure the indentation style is consistent (tabs not spaces) and opening braces are on the same line as the conditional or function statement, as well as making sure that the `ant` build (and embedded `jslint`) runs clean and you should be good to go.

But if things are getting screwed up a little bit, it may be easier in the short term to make sure you've secured any uncommitted changes and pushed them to your GitHub repository and then just blow away the `mxn` tree and re-fork. Sounds drastic but really isn't.

**Comment by vicchi** [comment]
You could also run the core tests in `mxn/tests/core.html` as well for any provider you've made changes to or for all providers if you've changed the MXN core in `mxn.js` or `mxn.core.js`.

**Comment by vicchi** [comment]
Now I'll try and cherry pick those two commits.

**Comment by vicchi** [comment]
So I've started to cherry-pick your commit `87a6bf0eb2a7aa5e468e65f3336759907e7a3845` for `mxn.ovi.geocoder.js` and something's not right. It looks like it reverts a change I made back in December last year to throw exceptions rather than display an `alert()` if the Ovi script isn't imported (commit `a3e14af0ac31fdc14162ac7cdbc89b59eddafdd3`) as well as the changes made in commits `6daf742a5482eedac8552988a9abd15ac1b4cbc2` for Pull Request #202 and `e80ff3414c6d2d4baea396255604a1637bc8b940` for Pull Request #222.

It's like your commit was based on a version of `mxn.ovi.geocoder.js` which is almost 5 months old and not from the latest `HEAD` of the `release-2.1` branch at all.

The same sort of thing applies to the changes to `mxn.ovi.core.js` as part of this commit.

This is getting more and more confusing. The more I look into this, the more I think you might just be better off saving your changes into a temporary directory, blowing away your repository, reforking and then manually re-applying the changes into the new, clean, version of the `release-2.1` branch and then issuing another Pull Request.

**Comment by esohns-humana** [comment]
Thanks for the information.

Well, that's just what I did, I merged upstream before submitting that pull request. I'll rebase my repository with upstream too, maybe that solves it.

**Comment by vicchi** [comment]
Which upstream branch? `master`, `integration` or `release-2.1` ... ?

**Comment by vicchi** [comment]
I can see you've closed this Pull Request ... is there another one in the works?

**Pull request closed without merging**
