### PR TITLE
Implementation of the load event in Google v2 provider

### PR DESCRIPTION
**Pull request by plopesc**
The implementation of that event in Google script.

Regards,

### CODE REVIEW

**Comment by freyfogle** [comment]
is this commit still valid? If so can you bring into sync with master? Thanks

**Comment by plopesc** [comment]
I don't know if last changes on master branch will cause some conflicts, but in projects based on idelab's branch, it works fine.

**Comment by freyfogle** [comment]
would be great to get all this merged in, can you please update to the current master and resolve the conflicts? 

I haven't looked in great detail, but I suspect it's just mxn.google.core.js

**Comment by dezfowler** [comment]
Not sure I understand what's going on here - seem to be a lot of files in this pull request as an addition where the same file already appears to be in the trunk.

Have these come in from different pull requests and the history been broken at some point?

Also, although I like the sound of the interactive stuff, I need to have a closer look at exactly what would be changing as it looks like it impacts on the core library too much.

**Comment by plopesc** [comment]
Hi
Interactive stuff includes some big changes in mapstraction. It was a big
challenge for me. It was packaged as a new extension for mapstraction
called idelabmapstraction. If you are now interested on it, we should study
the state of that extension and look for the best way to integrate it in
mapstraction.
Regards
El 26/02/2012 02:14, "Derek Fowler" <
reply@reply.github.com>
escribió:

**Comment by brunob** [comment]
Hi plopesc, i will have time soon to look at your mapstraction fork cause i need to allow map features editing on a project. I can help you to merge your fork with mapstration if you need help, i just need to look at it in details to know how this extension works.

When you say that "it was packaged as a new extension for mapstraction" do yo mean that we can use the original mapstraction side by side of your fork or do we need to load only the scripts of your fork ?

++

**Comment by vicchi** [comment]
I'm going to close this pull request down. Not because it's bad or invalid but there's several things that need to be addressed.
- The pull request is from the `master` branch. It really should be on a contribution specific branch as per MXN's [Contributing](https://github.com/mapstraction/mxn/wiki/Contributing) guidelines.
- It's for v2 of the Google Maps API, which was [officially deprecated by Google on 19 May 2010](https://developers.google.com/maps/documentation/javascript/v2/), which was also before this pull request was opened. Also, v2 of the Google Maps API is going away for good on 19 May 2013 (only 6 or so months from now).
- It's not clear whether this is standalone fork or a contribution into MXN; see [Bruno's comment](https://github.com/mapstraction/mxn/pull/49#issuecomment-4212138).

If you've updated your code to run under v3 of the Google Maps API; please put it on a (not `master`) branch and open a pull request for this, although from looking at the [fork's repository](https://github.com/idelab/mxn/commits/master) I can see that there's no been any activity since December 2010.

**Pull request closed without merging**
