### PR TITLE
removed version number from all openlayers references to make them all p...

### PR DESCRIPTION
**Pull request by gilesc50**
...ull the latest release. currently 2.12

### CODE REVIEW

**Comment by vicchi** [comment]
I can see various pros and cons to this ...

On the one hand, it cuts down on maintenance of the example and core test source files.

But on the other hand it makes testing problems further down the line challenging as we can't say for certain what version of a provider's API MXN version whatever has been tested against (see https://github.com/mapstraction/mxn/wiki/Map-API-Provider%3B-Feature-Support-Matrix for example).

Also and unrelated, one of the commits in this pull request (https://github.com/Earthware/mxn/blob/435c333326e6d8a60f1f35293015678df17fabff/source/mxn.openspace.geocoder.js) seems to do some reworking of the OpenSpace geocoder that isn't related to the removal of version numbers in OpenLayers ... should this commit be in this pull request?

**Comment by gilesc50** [comment]
That OpenSpace geocoder work should be in another pull request, sorry.

Well as long as we have it concistent I don’t mind. Some had a version number, some didn’t.
NB for bing and gooogle, we don’t get to fix the version, as they are always updating the apis. (you can fix the major version but that’s all)

Giles

**Comment by vicchi** [comment]
> That OpenSpace geocoder work should be in another pull request, sorry.

No worries. Will you issue a new one for this?

It's also an interesting point about Google and Bing updating their APIs. Based on this, I think we're fighting a loosing battle on maintaining a fixed and stable set of provider APIs on which to base MXN.

But I do think that, where possible, we should maintain the core tests and examples as working on a specific released of MXN and with as specific a version of the providers API as is possible. Yes, it'll mean more work for a new release, but I think it'll make life a bit easier when it comes to handling support requests and diagnosing errors with a given release and a given provider.

I'm open to suggestion but I'm minded not to merge this pull request for that reason; not because it's a bad pull request but because it might shoot us in the foot a few months down the line.

**Comment by gilesc50** [comment]
Well in that case please update all the references to be version 2.12 which is the latest openlayers then.

**Comment by vicchi** [comment]
Agreed. I've done a quick check and here's where we stand on provider versions ...

These are unchanged :-
- CloudMade is still on v0.8
- ArcGIS is still on v3.3
- Google v2 is on v2.441 and will stay that way until 19/5/13 when the v2 API will be obsoleted
- Google v3 is on v3.11 as of 19/2/13
- MapQuest and MapQuest Open are still on v7.0 as of 9/2/13
- Microsoft Bing v6 is still on v6.3
- Microsoft Bing v7 is still on v7.0
- Nokia Ovi is still on v1.0.12
- Yandex is still on v1.1

These have been updated since my last check :-
- Leaflet is now on v0.5 (up from v0.4.5)
- HERE and Nokia are now on v2.2.4 (up from v2.2.3)
- OpenLayers is now on v2.12 (up from v2.9.1)
- OS OpenSpace is now on v4.0 (up from v1.0.1)

So I'll make the changes for Leaflet, HERE, Nokia, OpenLayers and OpenSpace and re-test against these versions and update the docs as well.

**Comment by gilesc50** [comment]
Ok. Great.

Note though that Bing v7 .0 doesn’t mean it’s the same as before – they don’t increment the number when adding new features.
Google updates every quarter.

Maybe we should have a subfolder of examples that always pull the latest version of the api’s as well? (making it easier for us to check after new versions are released?)

**Comment by vicchi** [comment]
> Note though  that Bing v7 .0 doesn’t mean it’s the same as before – they don’t increment the number when adding new features.

True, but not much we can do about that.

> Maybe we should have a subfolder of examples that always pull the latest version of the api’s as well? (making it easier for us to check after new versions are released?)

Now that's an excellent suggestion ... can you open an issue for this so I don't forget?

**Comment by gilesc50** [comment]
Done: https://github.com/mapstraction/mxn/issues/232

**Comment by vicchi** [comment]
Cherry picked the OpenSpace geocoder changes and manually merged into the `release-2.1`; see commit 6878cb500d62f003bc6143a297d46d176ae2237e.

For all other changes in this comment, I'll action them as per the discussion thread and as per Issue #232

**Pull request closed without merging**
