### PR TITLE
Support for OneMap

### PR DESCRIPTION
**Pull request by nicodemuz**
Added very basic support for OneMap:
http://www.onemap.sg

A working demo can be found at:
http://www.nearbytutors.sg

Apologies for the messy code. Needs to be refactored a little bit.

### CODE REVIEW

**Comment by brunob** [comment]
Hi, thanks for your code. You don't need to put credits on top of your source file, these are added during mapstraction archive building.

Another point, i see that this api seems to be limited to singapor zone, am i it right ? I'd like to let other members of the team to tell if this should be provided in mapstration.

++

**Comment by nicodemuz** [comment]
That's right. OneMap is only for the Singaporean market.

**Comment by maysam** [comment]
very handy support

**Comment by freyfogle** [comment]
In my opinion the more providers the better, why limit ourselves only to global providers? I see no reason not to add it

**Comment by brunob** [comment]
Ok, we seems to agree about donig this merge in mapstraction (at least to of us ^^). Can you cleanup your files as i mentionned in my previous comment before we merge it ? If you can't do it, let me know and i'll try to make it one of these days.

**Comment by nicodemuz** [comment]
Actually, OneMap is based on ArcGIS / ESRI. If there was support for ArcGIS, it would be very easy to implement support for OneMap as well.

**Comment by dezfowler** [comment]
It would be good to get support for ArcGIS proper into the library if I'm understanding correctly that OneMap is just a tile layer for that.

**Comment by vicchi** [comment]
What's the current status on this pull request? @ajturner has a current pull request (#163) to add ESRI support into MXN. Once this goes into the codebase, is OneMap needed as a dedicated provider?

**Comment by ajturner** [comment]
@MrNicodemuz & @dezfowler ArcGIS is now a supported provider. do you want to make OneMap work now?

**Comment by vicchi** [comment]
It's worth pointing out that all the recent changes to the code base, including @ajturner's ESRI provider support is currently on the `integration` branch and not on `master`.

**Comment by vicchi** [comment]
As Mapstraction now has ESRI ArcGIS support and there's been no response from @MrNicodemuz for almost a year I'm closing this pull request. The v2.1 code base has changed significantly from that which the pull request was based on, but feel free to re-issue this based on the current code base.

**Pull request closed without merging**
