### PR TITLE
Esri provider and example

### PR DESCRIPTION
**Pull request by ajturner**
Much cleaner diff of files for the new provider.

### CODE REVIEW

**Comment by vicchi** [comment]
Thanks Andrew - I can see in the ESRI example that it's using Dojo. Is this automagically provided when you include the ESRI JS source or is this an artifact of your local environment? Just checking ...

**Comment by vicchi** [comment]
Two more comments ...

I can see quite a few console.log statements in mxn.core.esri.js ... I'm assuming these are for debugging purposes and should be stripped out.

Also, the ESRI example code does a `map.addControls({zoom:true, layers:true});` but I don't see a layers control defined in the core nor in the ESRI implementation?

**Comment by vicchi** [comment]
... and ditto for the notion of `legend` controls?

**Comment by ajturner** [comment]
Dojo is a built-in requirement for the Esri JS API. This will be ~~going away~~ becoming more transparent to the developer  in a future release

You are right the console.log should be stripped out. There ~~isn't yet a layers or legend control that I'm aware of~~ is a layers & legend control that I need to add. I was just trying to model the existing example code calls.

**Comment by vicchi** [comment]
I couldn't see an explicit include of Dojo ... so I'm assuming it's packaged as part of the ESRI include.

I'll strip out the `console.log` statements and the `layers` and `legend` controls from the test file. No need for you to do that.

**Comment by vicchi** [comment]
Oops. Clicked on `Close and Comment` and not `Comment`. Need more coffee.

**Comment by ajturner** [comment]
Sorry -  clarifying my previous comment. Dojo is bundled into the Esri js build. 

I also found out there is a Legend & Layers control, so I'll add those in. I guess for the next release?

**Comment by vicchi** [comment]
Excellent ... thanks Andrew. I'll get this merged in over the next couple of days.

**Comment by ajturner** [comment]
Cleaned up the code & now passes the core tests.

**Comment by vicchi** [comment]
Thanks Andrew - that's much better. The core tests all pass and the example code seems to work. I'll get these changes commited into the `integration` branch.

**Comment by vicchi** [comment]
Manually merged into the `integration` branch; see commit cf43374fb1cbd53b527ee64974393f27476ca298

**Pull request closed without merging**
