### PR TITLE
Polyline / event updates to Google V3

### PR DESCRIPTION
**Pull request by adamd**
I just realized that these changes I made awhile ago didn't make their way into Mapstraction due to my misunderstanding of how Git and Github work.

### CODE REVIEW

**Comment by adamd** [comment]
I created a branch, but was never able to get it to show up on GitHub. So, this full request is from my master, which I guess defeats the purpose of creating a branch. Sorry about that--I'm still getting the hang of this.

**Comment by adamd** [comment]
Obviously getting the hang of it, since I just accidentally closed the request. :)

**Comment by dezfowler** [comment]
Not sure what's going on here - MapQuest rather than Google V3 changes?

**Comment by adamd** [comment]
Hey Derek,

I did some Open MapQuest stuff. As for the Github message, I'm still
struggling to use it to contribute the right way. Sorry for the confusion.

On Wed, Nov 16, 2011 at 1:35 PM, Derek Fowler <
reply@reply.github.com

**Comment by freyfogle** [comment]
basic framework for openMQ provider. not sure if working or not

**Pull request merged**
