### PR TITLE
openBubble and closeBubble refactoring + add of mxn event fire for both ones

### PR DESCRIPTION
**Pull request by brunob**
This is a refactoring of openlayers bubbles methods (as we do it in googlev3) to calls the fire and close events when needed.

### CODE REVIEW

**Comment by brunob** [comment]
Oops, i realised that i've already got a patch for this which was lost after merge problems. Here the patch for another approach :

https://gist.github.com/2168921

++

**Comment by brunob** [comment]
In fact, my second proposed version is much in the way we already handle it on other api's : just open a bubble on click and don't close it if marker is clicked again. The actual implementation, and my first proposed patch handle the second click on the marker to close the opened bubble.

Maybe we should start to look at all differents implementations to be shure that all APi's do the same thing. This could be done by focus on one API with all funtions implemened, and start to say to contributors that this APi is a king of reference. What do you think of it ?

**Comment by vicchi** [comment]
So it's not clear to me whether this pull request needs to be actioned, whether the patch needs to be applied or whether this is part of something a bit larger (the "king of reference for the APIs") ... which one is it? I want to get the pull requests locked down and cleaned up but this is by no means clear, at least to me.

**Comment by vicchi** [comment]
@brunob What's the status on this ... it's been open for over a year now?

**Comment by brunob** [comment]
Hi @vicchi this commit was here to make openlayers act like others APIs (there was an inconsistency between googlev3 and openlayers for example). I think this can still be merge, but i'm not sure cause i'm not following Mapstraction project since a long time for now :(

Anyway, thanks for the great job you're doing on the project :)

**Comment by vicchi** [comment]
I could be wrong but I think this Pull Request is now redundant. Take a look at commit 0c778da0b7e680a0d3c1e7e3c623a4f310c4525c, part of Pull Request #222. This commit migrated from `OpenLayers.Marker`, which is now obsoleted, to `OpenLayers.Feature.Vector`. In particular, the use of the `overFeature` and `outFeature` property handlers.

I think that this effectively replicates what you were trying to be, albeit via another way of doing things? Could you take a look when you have a moment?

This is (currently) the last open Pull Request ... I'd really like to get it actioned and closed!

**Comment by brunob** [comment]
Hi @vicchi no problem to close this pullreq since what i see in the commit you cited, gogogo for the next release ;)

**Pull request closed without merging**
