### PR TITLE
added optional parameter to request multiple results from the geocoder a...

### PR DESCRIPTION
**Pull request by gilesc50**
...pi, and implemented it in open layers and the corresponding example. Existing api that returns just 1 result is uneffected, so this is a non-breaking change. Gary please confirm this approach is acceptable before I go ahead and implement the same in all the other geocoder modules (on this same pull request). Thanks, Giles

### CODE REVIEW

**Comment by vicchi** [comment]
Not too sure why the `googlev3-geocoder.html` example file has a var called `microsoft_key` in it ... the perils of using a previous source file as boilerplate for a new file perhaps?

Can't see this var being used anywhere in that file so I assume it's OK to excise it.

**Comment by vicchi** [comment]
So I've got this locally merged and everything seems to work; or at least nothing breaks. But I'm not 100% sure about the returns I get from the example files.

Using a query string of "teddington", I get the following:

Google v3 - a single return for the Teddington in SW London, with the InfoBubble showing "Teddington, England, United Kingdom"

Microsoft 7 - 2 returns, "Teddington, England, United Kingdom" (the SW London one) and "Teddington, England, United Kingdom" (the Gloucestershire one).

OpenLayers - 3 returns, one in SW London as ", England, United Kingdom", one in Australia as ", , Australia" and one in New Zealand as ", Canturbury, New Zealand"

Ovi - 3 returns, one in SW London as "Teddington, Middlesex, GBR", one in Gloucestershire as "Teddington, Tewkesbury, Gloucestershire, GBR" and one in Australia (different to the OpenLayers return) as "Teddington, Queensland, AUS".

I can live with the differences in returns as each geocoder varies but I'm surprised by the single hit for the Google v3 geocoder and more worried about the formatting of the return from the OpenLayers geocoder.

Can you take a look and see if you get the same results?

**Comment by gilesc50** [comment]
Yes absolutely - doh.

**Comment by gilesc50** [comment]
Sure will do. Google's number of results varied for me for different searches.

**Comment by vicchi** [comment]
PS: I've edited your last two comments to remove your contact details; that's the problem with replying via email.

**Comment by vicchi** [comment]
Fixed bug in parsing the return value from the OpenLayers geocoder, checking for town, village and hamlet in addition to city.

Manually merged into `integration` branch; see commit 6daf742a5482eedac8552988a9abd15ac1b4cbc2.

**Pull request closed without merging**
