### PR TITLE
Add support for Nokia Maps

### PR DESCRIPTION
**Pull request by vicchi**
So I've just effectively cloned the old Ovi Maps code to add Nokia Maps support. This is effectively a straight copy and then global search and replace from the `ovi.mapsapi` JS namespace to the `nokia.maps` JS namespace. The only major change is that the `mapviewchangeupdate` event (for panning, zooming, etc) has been changed to the `mapviewchange` event.

I've done a reasonable (though not exhaustive) amount of testing and it _seems_ to work; it also builds clean up `ant` with no `jslint` errors or warnings.

As a side note, I've left the _old_ Ovi Maps code in the code base, whilst it's effectively obsoleted by Nokia Maps, the API is still up and running, for now at least.

### CODE REVIEW

**Comment by vicchi** [comment]
PS: Commit `5691bcb` can be ignored; that was caused by me merging the master upstream commits into my fork to bring it up-to-date with the main MXN repository.

**Comment by ajturner** [comment]
Looks good - however there are some discrepancies in the code formatting. There shouldn't be a space in between function names and their parens - e.g.  "function ()" should be "function()" to follow the rest of the Mxn syntax.

Also is there a demo page?

**Comment by vicchi** [comment]
If you want me to fix up the formatting, I'll happily do so. However, it's worth pointing out that the lack of a space between the function name and the argument list seems to be the only MXN coding standard there is. I've taken a quick look at other implementations in the code base and the style differs wildly, both between implementations and inside a single implementation file.

There's a very simplistic demo page up at http://maps.vicchi.org/mxn-nokia.html.

**Comment by vicchi** [comment]
Just fixed up the code formatting, see commit https://github.com/vicchi/mxn/commit/d386e1fe4d6e67931f2b601eed9a4ea0017ec346

**Comment by brunob** [comment]
Hi Gary, it seems ok for me to merge this pull req. I'm just curious about 35c5eb3 which modify mxn.js just for a problem about wordpress. If that modification is bug free, why not.

**Comment by vicchi** [comment]
Hi Bruno,

The src parameter for any JS include should be able to be a well formed URI, accepting or ignoring any query parameters it does or doesn't want. man.js will barf if there's query parameters that it doesn't recognise which isn't good behaviour. So I changed the reflex to allow mxn.js to only care about the map provider arguments and ignore everything else. Yes, this came up duri testi with WordPress but the principle isn't WordPress specific, just good JS behaviour. Hope this makes sense.

-Gary

**Comment by vicchi** [comment]
Apologies for the awful spelling there. My iPad seems to be in damn you autocorrect mode this morning!

**Comment by brunob** [comment]
Thanks for this explaination Gary, this seems ok to me to merge this pull req.

**Comment by vicchi** [comment]
So ... someone want to merge this or should I as it has Bruno's blessing :-)

**Comment by vicchi** [comment]
This pull request should be closed; it's now superseded by https://github.com/mapstraction/mxn/pull/159 and by https://github.com/mapstraction/mxn/pull/160

**Pull request closed without merging**
