### PR TITLE
Various code fixes and new methods on Polyline, Marker, and Mapstraction

### PR DESCRIPTION
**Pull request by nrabinowitz**
Hello! I'm using the Mapstraction library as a dependency for the next version of my timemap.js library, which helps developers make maps and timelines (using SIMILE Timeline) that work together - see http://code.google.com/p/timemap/ for more info. I ran into a few BoundingBox bugs, which I fixed, and added a BoundingBox#getCenter method, which is found in the Google API. (I did a very simple implementation, treating lat/lon as cartesian coords - I think there might be a more accurate approach, but this seemed sufficient). I also tweaked the build file to stop emitting a deprecation warning for "args".

Let me know if you have any questions, and thanks for a great library! I may have a few more tweaks as I proceed to integrate the library into my project.

### CODE REVIEW

**Comment by nrabinowitz** [comment]
I updated the commit range for this pull request - as you can see, I've done quite a bit more work:
- Added or fixed provider code for various existing methods
- Added show() and hide() methods to Polylines in mxn.core, google, googlev3, openlayers, microsoft, and yahoo
- Added support for click events to Polylines (core, same providers as above)
- Added isHidden() method to both Markers and Polylines (core, same providers as above, using provider-specific implementations where available)
- Added map-based (rather than marker-based) showBubble() and hideBubble() methods (core, same providers as above minus yahoo)

I'd love to see all this moved into the official library when you get a chance. I am currently distributing my fork as part of the timemap.js 2.0 distribution package, which requires the functionality and fixes I've added, but would love to distribute the official branch instead.

Thanks, and please let me know if you have any questions!

-Nick

**Comment by dezfowler** [comment]
Quite a bit of work indeed, very large number of changes here. 

Some undoubtedly should go in however there are a few others here I'm less sure about. Some I know would definitely break things and others I just don't think the majority of users will need. Not sure whether it's possible to cherry pick commits in git but I'll see what I can do. I'll comment on the ones I don't think should go in so you know what's what.

Thanks,
Derek

**Comment by nrabinowitz** [comment]
Thanks - I'm happy to help in whatever way I can. Note that a couple of the commits here do introduce issues that get fixed in later commits, which might complicate a commit-by-commit approach. 

I would really like to see the functionality here get added to the official library; everything I've added is needed for integration with the Timemap.js library, and I'd much rather work with you to support this in the core library than get into the position of permanently maintaining my own fork.

I'm most familiar with the Google APIs, and most of the things I've added here are intended to reproduce functionality supported in by those providers (as well as several others in most cases). While I totally understand that you would rather keep little-used functionality out of the library, the fact that several providers have chosen to include these methods and events in their own code might suggest that they do in fact support common use-cases.  At a basic level, the functionality I've added here is based on the idea that every placemark you add to the map (including polylines) should support click events, show/hide, and opening an info bubble. I'm planning further work to extend this idea to image overlays as well, making a mxn.ImageOverlay class supporting the same basic functionality. 

Let me know if you'd like to discuss this further - I'm very interested in seeing the Mapstraction library get to a robust and stable point, and I'd be happy to help to the extent I can.

**Comment by nrabinowitz** [comment]
Whoops, sorry, didn't mean to close the pull request just now - my mistake.

**Comment by freyfogle** [comment]
Hi is this pull request still relevant? Apologies I know it's been a long time. I'm keen to kill the pull request queue

**Comment by nrabinowitz** [comment]
Yes, it's still relevant, in that I'm still maintaining a fork with these changes for Timemap.js users, and I'd love to merge my additions with the core library. I believe, however, that all of the @palewire commits have probably been pulled already via [this pull request](https://github.com/mapstraction/mxn/pull/101). 

It's been a while, however, and I haven't merged the Mapstraction master with my fork recently. Would it make sense for me to close this pull request, merge the current Mapstraction master into my fork, and then open a new pull request with the remaining changes? (I'm still a little hazy as to how Git works in cases like this.)

**Comment by freyfogle** [comment]
Yeah, that's why I asked, it wasn't clear to me if this was covered by @palewire's branch, etc

Please do merge with the master and then open a new request. I hope that it will reduce the diffs to very few. Let's solve it. Good luck.

**Comment by nrabinowitz** [comment]
Ok, I'll close this and open a new request when I've had the chance to merge my fork.

**Pull request closed without merging**
