### PR TITLE
Patched Leaflet icon to work with changes in the trunk set for version 0.4

### PR DESCRIPTION
**Pull request by palewire**
Meant to address issues brought to my attention by @freyfogle and logged in issue #114. 

What of reverse-compatibility? Do we need to worry at this early stage in Leaflet's development, or should we require users to upgrade to 0.4 when the time comes?

Also, either way, when is the right time to roll this into trunk at MXN?

### CODE REVIEW

**Comment by palewire** [comment]
I've tried to use hasOwnProperty instead of a check again L.VERSION since VERSION seems to be a bit farked up. The content is actually a string, and not good for <> testing. See: https://raw.github.com/CloudMade/Leaflet/master/dist/leaflet.js

**Comment by dezfowler** [comment]
If Leaflet is still pre-release then I wouldn't worry about backward
compatibility until after v1 of it comes out.

What we should do is track which version of the Leaflet API  Mapstraction
is updated for.

Derek
On Mar 15, 2012 12:09 AM, "Ben Welsh" <
reply@reply.github.com>
wrote:

**Comment by freyfogle** [comment]
Leaflet may officially be pre-release, but the reality it is widely used and increasingly popular. I see more and more people using it, my guess is it will soon overtake openlayers as the library of choice for accessing OSM. The documentation is much superior and it's being much more actively developed. We discussed this at last #geomob event here in London and there was general agreement. To be honest, I would not be surprised if mapquest stops supporting their own open library and just uses leaflet. 

So, I'm inclined to merge this, as I think it's important for mxn to support leaflet. 

That being said, it would of course be better if leaflet's API were more stable.

**Comment by brunob** [comment]
So, what is the point on this pull request ? Should i merge it ?

**Comment by dezfowler** [comment]
As I said - I don't think it's necessary to have any kind of backward compatibility. Mapstraction should just work with a particular Leaflet build, which may be the latest nightly or whatever. We just need to document in the source or on the wiki that the provider is under development and is updated for Leaflet build x.x.

Adding code for backward compatibility just bloats the library.

**Comment by brunob** [comment]
I guess this mean that we should close this pullreq, i leave it to you to decide ;)

**Comment by dezfowler** [comment]
@palewire Are you able to amend this so it doesn't do the version checking and just works with the 0.4 API?

**Comment by vicchi** [comment]
Manually merged in Leaflet icon handling fix in commit 8df437a56aa1d47d48a88c9a20fa2d0497accb5f. The Leaflet code base now works with the current stable release,  currently 0.4.5, released October 25, 2012.

**Pull request closed without merging**
