### PR TITLE
Added code for the implementation of the openBubble and closeBubble, but...

### PR DESCRIPTION
**Pull request by gilesc50**
... openmq doesn't seem to have these. only a toggle option which reverses the state. This is better than nothing happening though.

### CODE REVIEW

**Comment by vicchi** [comment]
You're right. It is better than nothing but I think it needs something more. In line with the other map API providers what I would expect to happen is something along the lines of the following ...
- calling `openBubble()` on a marker with no open InfoBubble - the bubble opens
- calling `openBubble()` again, now that an InfoBubble is open - no action, the bubble is already open
- calling `closeBubble()` on the same marker - the bubble closes
- calling `closeBubble()` again - no action, the bubble is already closed

... but what happens instead is ...
- calling `openBubble()` on a marker with no open InfoBubble - the bubble opens
- calling `openBubble()` again, now that an InfoBubble is open - the bubble closes
- calling `closeBubble()` on the same marker - the bubble re-opens
- calling `closeBubble()` again - the bubble closes

... now this makes perfect sense given that the MQ Open API just implements a toggle but it's counter intuitive when viewed in the context of how MXN should work and how the other API providers work.

I think we need to maintain some form of internal state within the Marker object and only call `toggleInfoWindow()` when the action that will take is known to be correct within the semantics of `openBubble()` and `closeBubble()`.

But it gets better. I've tried implementing this, with the known gotchas described above, and whilst I can get an `InfoBubble` to open, I can't get the bubble text to actually display. In other words, there's an empty bubble which contains no text. Could you take a look at this perhaps?

**Comment by vicchi** [comment]
Also ... I've updated the `openmq` provider code to support polylines correctly. You might want to re-fetch from the `integration` branch. See commits b7341d6a2b927003b0e13e086be928dc18b24eb9 and bba7004f608b4a1e6eb1069e43a1076cca169266.

**Comment by vicchi** [comment]
Fixed the empty `InfoBubble` text issue. Now working on the internal state to control `toggleInfoWindow()`.

**Comment by vicchi** [comment]
Fixed the internal state handling and fully implemented `openBubble()` and `closeBubble()`. See commit 2c6e7622d26d0be2fb7d7932955d0260f03bcfc8. I'll close down this pull request as in effect this commit is a manual merge of your changes, plus my additions to maintain the `InfoBubble` state and to correctly set the content of the `InfoBubble` when creating/showing it.

**Comment by gilesc50** [comment]
Gary

That’s great, but I did wonder though, because we expose the underlying openmq propriety marker, its possible someone could use that to open the info bubble and hence mess up your state? However that aside, openmq also opens the popup when you click the pin, which I think can also play havoc with your state. To see this:
1. ```
    Load mxn/examples/openmq.htm in a browser
   ```
2. ```
    Now click the Demo function: add a marker
   ```
3. ```
    Now click the Demo function: Show an info bubble
   ```
4. ```
    Now click the Demo function: Hide an info bubble
   ```
5. ```
    Now click the pin (note its showing a finger cursor now and wasn’t before) and it opens the bubble
   ```
6. ```
    Now click the Demo function: Show an info bubble and it actually hides it ☹
   ```

regards

Giles

**Comment by vicchi** [comment]
I'll take a look now

**Pull request closed without merging**
