### PR TITLE
Yandex: fix errors in commits 3c33ba88078af and e176c798821fa7.

### PR DESCRIPTION
**Pull request by ChALkeR**
I hope this is a correct fix.

### CODE REVIEW

**Comment by gilesc50** [comment]
Manually merged in the last of these changes into release 3.0, so closing this issue. We don't need this line: (args.zoom || args.zoom == 'large') so I left that out, as it would have defaulted to small already.

**Comment by ChALkeR** [comment]
No, it's broken right now and you left it broken.

How can I tell it to use large controls now? That's just not possible.

It will be ok if you just copy the code from mxn.yandex2.core.js, btw.

**Comment by ChALkeR** [comment]
The current code:

```
    if ('zoom' in args) {
        if (args.zoom || args.zoom == 'small') {
            this.addSmallControls();
        }

        else if (args.zoom == 'large') {
            this.addLargeControls();
        }
    }
```

How is that supposed to work?

**Comment by ChALkeR** [comment]
`this.addLargeControls();` is just not reachable in that if-else-if block.

**Comment by ChALkeR** [comment]
Code from mxn.yandex2.core.js is ok:

```
    if ('zoom' in args) {
        if (args.zoom === true || args.zoom == 'small') {
            this.addSmallControls();
        }

        else if (args.zoom == 'large') {
            this.addLargeControls();
        }
    }
```

It's better just to use that same code for consistency.

At the time of me writing this pull request there was no mxn.yandex2.core, and other providers behavior is incosistent, so I did it the other way.

**Comment by gilesc50** [comment]
ok I will swap it to the yandex2 code.

**Comment by ChALkeR** [comment]
Thanks =).

**Comment by gilesc50** [comment]
Done,

**Comment by ChALkeR** [comment]
Nice.

**Pull request closed without merging**
