### PR TITLE
Fix large zoom controls for Yandex.Maps.

### PR DESCRIPTION
**Pull request by ChALkeR**
Fix a mistype. This is a one-liner.

http://api.yandex.ru/maps/doc/jsapi/1.x/ref/reference/smallzoom.xml
http://api.yandex.ru/maps/doc/jsapi/1.x/ref/reference/zoom.xml

I have verified that it works as expected.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Hope I sent the request to the right repo.
I can rebase, if you wish.

**Comment by vicchi** [comment]
Hi. You've got the right repository. Thank you for this and thank you for contributing.

The current Yandex support in Mapstraction is based on the Yandex 1.x API. I'd like to get Mapstraction to support the new Yandex 2.0 API but this version is very different to the 1.x version and will need quite a bit of work to get it up and running.

Is this something you could help with?

-Gary

**Comment by ChALkeR** [comment]
Yes, v2.0 is nicer (it's more pretty and does not requre a key).
A question here: do you want it to replace mxn.yandex.geocoder.js and mxn.yandex.core.js, or do you want it to be named yandex2?

mxn.yandex.geocoder has some (trivial) bugs, do they need to be fixed or just replaced with a v2 api?

**Comment by ChALkeR** [comment]
I have an already working geocoder based on v2 api.

**Comment by ChALkeR** [comment]
Geocoder still has a problem, I described it in the commit.
The solution would be to discard the country parameter from the input if it looks like a country code (short and all-caps).

And I'm still not sure if returning "ThorughfareName, PremiseNumber" as street is good, but this is how Yandex.Maps names it.

**Comment by ChALkeR** [comment]
Off-topic: nominatim.openstreetmap.org got fixed today (CORS issues), so OpenLayers geocoder works for me now, too.
https://github.com/twain47/Nominatim/commit/0dd10c3fff9896ca23b884a7ec7a97002065d083
https://github.com/twain47/Nominatim/commit/490190b8739241b84ead87ed47f8a3c65553fe10

It wasn't working before.

**Comment by vicchi** [comment]
Wow. You've been busy!

> A question here: do you want it to replace mxn.yandex.geocoder.js and mxn.yandex.core.js, or do you want it to be > named yandex2?

Given the precedent MXN has with the Google and Microsoft implementations and as the Yandex v2 API is a complete change from v1.x, I think the provider should be `yandex2` as a new provider, rather than changing the `yandex` provider.

> mxn.yandex.geocoder has some (trivial) bugs, do they need to be fixed or just replaced with a v2 api?

Fixed in the `yandex` (v1.x) implementation I think.

> I have an already working geocoder based on v2 api.

Thanks.

> Geocoder still has a problem, I described it in the commit.
> The solution would be to discard the country parameter from the input if it looks like a country code (short and all-
> caps).
> 
> And I'm still not sure if returning "ThorughfareName, PremiseNumber" as street is good, but this is how
> Yandex.Maps names it.

That seems a viable work-around. Each geocoder I've come across has its own view of how to name and handle address components.Your work-around ties in with the other MXN geocoder implementations so I think we're good.

-Gary

**Comment by ChALkeR** [comment]
Ignoring country codes added.

**Comment by ChALkeR** [comment]
I don't think i will have enogh time in the near future (until January) for implementing the yandex2.core.js. That'll probably make it a new pull request.

Do you think you can merge this (after reviewing the code)?

Btw, what's up with the releases?

**Comment by vicchi** [comment]
I totally appreciate that. I'm working on the new release on the `integration` branch when time permit. I don't realistically see the next formal version of Mapstraction coming out until sometime in January either.

For now, the head of `integration` is pretty stable; it builds clean under ant and passes all of the core tests. It paints a pretty good picture of what the next release will look like but there's still some work to do to make all the implementations as functionally equivalent as they can be.

I'll review and merge this pull request as soon as I have time to do so; either tonight (unlikely) or by the end of the week (much more likely).

-Gary

**Comment by vicchi** [comment]
Manually merged into `integration` branch; see commit 49e44b612cce4545775e95cac9d908869be0886f.

**Comment by ChALkeR** [comment]
Thanks.

**Comment by ChALkeR** [comment]
https://gist.github.com/4339644 — that's all for now.
I got that working for my current needs (just the basic map and a single marker).
I'll finish that when I'll have some spare time.
It can be used as a starting point.

**Comment by ChALkeR** [comment]
Screenshot

**Pull request closed without merging**
